definitions:
  pb.CreateLogisticRequest:
    properties:
      amount:
        type: integer
      destinationName:
        type: string
      duration:
        type: string
      logisticName:
        type: string
      originName:
        type: string
    type: object
  pb.CreateLogisticResponse:
    properties:
      id:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  pb.FindOneData:
    properties:
      amount:
        type: integer
      destinationName:
        type: string
      duration:
        type: string
      logisticName:
        type: string
      originName:
        type: string
    type: object
  pb.FindOneResponse:
    properties:
      data:
        $ref: '#/definitions/pb.FindOneData'
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /logistic:
    get:
      description: Get a logistic based on given parameter
      parameters:
      - description: test example
        in: query
        name: origin_name
        required: true
        type: string
      - description: test example
        in: query
        name: destionation_name
        required: true
        type: string
      - description: Authorzation(Bearer random_value)
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pb.FindOneResponse'
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Find a logistic data
      tags:
      - Logistic
    post:
      description: Create a new logistic data and return a message
      parameters:
      - description: Create a new logistic data
        in: body
        name: create
        required: true
        schema:
          $ref: '#/definitions/pb.CreateLogisticRequest'
      - description: Authorzation(Bearer random_value)
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pb.CreateLogisticResponse'
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Create a new logistic data
      tags:
      - Logistic
swagger: "2.0"
