---
version: '3'
services:
  api-gateway:
    build: ./api-gateway
    restart: on-failure:5
    environment:
      - AUTH_SVC_URL=auth-svc:50051
      - LOGISTIC_SVC_URL=logistic-svc:50052
    ports:
      - "3000:3000"
    links:
      - auth-svc
      - logistic-svc
  auth-svc:
    build: ./auth-svc
    restart: on-failure:5 
    ports:
      - "50051:50051"
    environment:
      - DB_URL=postgres://orderfaz:orderfaz@postgresql:5432/orderfaz
    depends_on:
      - postgresql
    links:
      - postgresql
  logistic-svc:
    build: ./logistic-svc
    restart: on-failure:5 
    ports:
      - "50052:50052"
    environment:
      - DB_URL=postgres://orderfaz:orderfaz@postgresql:5432/orderfaz
    depends_on:
      - postgresql
    links:
      - postgresql
  postgresql:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: "orderfaz"
      POSTGRES_DB: "orderfaz"
      POSTGRES_PASSWORD: "orderfaz"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data/pgdata
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
networks:
   default: